### ISSUE TITLE
Running locally no longer works (after webworker changes)

### ISSUE THREAD

**Issue by nouyang-curoverse** [abeconnelly/untap#10]
On chromium & google-chrome browsers I get 

`Uncaught SecurityError: Failed to construct 'Worker': Script at     'file:///home/nrw/projects/untap/html/js/untap-sql-worker.js' cannot be accessed from origin 'null'.`

On fIrefox, I have similar URI issues 

`NS_ERROR_DOM_BAD_URI: Access to restricted URI denied`

but can get around by changing my FF settings as according to 
http://stackoverflow.com/questions/21855355/loading-a-text-file-through-ajax-gives-restricted-uri-error

**Comment by abeconnelly** [comment]
Trying to run the visualization front end by opening the file directly in the browser won't work properly.  Using a web server (nginx, apache, etc.) should be used.
