### ISSUE TITLE
Update HTML schema description with enrollment table

### ISSUE THREAD

**Issue by abeconnelly** [abeconnelly/untap#14]
The HTML files need to be updated to include the new `enrollment` table and CSV/TSV files included in the snapshot.  The following HTML file should be updated:
- [`untap.html`](https://github.com/abeconnelly/untap/blob/master/html/untap.html)

The `Overview` section needs to give a link to the new `enrollment.tsv` file.  The `Schema` tab needs to have the schema for the new `enrollment` SQL table.  The `Schema Quick Reference` modal (upper right hand corner button) needs to be updated to include the new `enrollment` SQL table.

**Comment by swzCuroverse** [comment]
I am currently working on this.

**Comment by abeconnelly** [comment]
Resolved by https://github.com/abeconnelly/untap/commit/211bf1366e10ed5b2e3f40e5f4c0db42fc498177
