### ISSUE TITLE
Add geographic to the scraped data

### ISSUE THREAD

**Issue by swzCuroverse** [abeconnelly/untap#19]
Geographic data for participants is available in tapestry.  Scrap and make available in untap.  This is an enhancement request, but I wanted to track it here.

**Comment by abeconnelly** [comment]
The table `geographic_information` has been added with the `state` (full state name, no abbreviations) and `zip`.

For example, here is the result of `select * from geographic_information limit 10`:

```
id  human_id    state   zip
1   hu43860C    Massachusetts   02446
2   huBEDA0B    New York    10012
3   huE80E3D    North Carolina  
4   hu9385BA    Michigan    48103
5   huAE6220    New Hampshire   03110
6   hu034DB1    Colorado    80302
7   hu6E4515    Massachusetts   02138
8   huA90CE6    Massachusetts   02445
9   hu34D5B9    Massachusetts   02144
10  hu97DB4A    California  95128
```
